import { LivestockDiagnosis } from '../Models/LivestockHealth';
import Livestock from '../Models/Livestock';
import Farm from '../Models/Farm';
import User from '../Models/User';
import WeatherData from '../Models/WeatherData';
import cloudinary from '../Config/cloudinary';
import logger from '../Utils/logger';
import { createNotification } from './notification.service';
import { sendBrevoEmail } from './email.service';
import { livestockHealthService } from './livestock-health.service';
import { Types } from 'mongoose';
import { analyzeImageWithGemini, chatWithContextDetailed, getModelName } from '../Utils/geminiClient';
import { buildVetDiagnosisChatSystemPrompt } from '../Utils/vetPromptRouter';
import { getHerdPreventionAdvice } from '../Utils/herdPreventionAdvice';
import { formatVetAiStructuredResponseToText, parseVetAiStructuredResponse } from '../Utils/vetStructuredResponse';
import { addLivestockDiagnosisJob } from '../Queues/livestockDiagnosis.queue';

/**
 * Livestock Health Diagnosis Service
 * Uses AI to analyze images of livestock and provide health assessments
 */

// AI Prompt for livestock health analysis
const LIVESTOCK_DIAGNOSIS_PROMPT = `You are an expert veterinarian AI assistant specializing in livestock health assessment. Analyze the provided image(s) of the animal and provide a comprehensive health diagnosis.

**Animal Information:**
- Species: {species}
- Breed: {breed}
- Age: {age}
- Current Health Status: {healthStatus}
- Recent Health History: {healthHistory}
{batchInfo}

**Environmental Context:**
- Location: {location}
- Weather: {weather}
- Temperature: {temperature}°C
- Humidity: {humidity}%

**Instructions:**
1. Carefully examine the image(s) for visible signs of illness, injury, or abnormality
2. Look for: skin conditions, posture problems, eye/nose discharge, swelling, wounds, parasites, coat/feather condition
3. Consider the species-specific health indicators
4. Provide confidence level for your assessment
5. If this is a batch with multiple affected animals, consider disease spread risk and recommend isolation/quarantine accordingly
6. If a contagious disease is plausible, include prevention steps for the UNINFECTED animals (protect the rest of the flock/herd). Mention vaccination ONLY when a known vaccine exists; if no vaccine exists, explicitly say so.

**Response Format (JSON):**
{
  "diagnosis": "Primary condition identified",
  "confidence": 0.0-1.0,
  "severity": "low|moderate|high|critical",
  "symptoms": ["List of observed symptoms"],
  "possibleConditions": [
    {
      "name": "Condition name",
      "probability": 0.0-1.0,
      "description": "Brief description"
    }
  ],
  "treatment": [
    {
      "priority": 1,
      "action": "Treatment step",
      "timing": "When to apply",
      "notes": "Additional notes"
    }
  ],
  "prevention": ["Preventive measures"],
  "urgency": "immediate|within_24h|within_week|routine",
  "veterinaryRequired": true|false,
  "quarantineRecommended": true|false,
  "spreadRisk": "Description of disease spread risk if applicable",
  "followUpDays": 7,
  "additionalNotes": "Any other relevant information"
}`;

// NOTE: Vet chat prompts are generated by buildVetDiagnosisChatSystemPrompt() (species-specialized).

const buildVetJsonRepairMessage = (args: { userMessage: string; invalidOutput: string }) => {
  const bad = String(args.invalidOutput || '').slice(0, 6000);
  return `Your previous response was not valid JSON or did not match the required schema.\n\nFarmer message:\n${args.userMessage}\n\nInvalid output (truncated):\n${bad}\n\nReturn ONLY a corrected JSON object that matches the schema. No markdown. No code fences.`;
};

export class LivestockDiagnosisService {
  private isHealthyDiagnosisText(text: unknown): boolean {
    if (typeof text !== 'string') return false;
    const t = text.toLowerCase().trim();

    // Keep this intentionally conservative: only mark "completed" when it's clearly healthy/no-issue
    return (
      t === 'healthy' ||
      t.includes('no disease') ||
      t.includes('no issues') ||
      t.includes('no issue') ||
      t.includes('normal') ||
      t.includes('no visible problem')
    );
  }

  private normalizeDiagnosisStatus<T extends { status?: any; diagnosis?: any; severity?: any }>(doc: T): T {
    if (!doc) return doc;

    // Normalize legacy/LLM severity values (prevents Mongoose enum validation errors on save).
    if ((doc as any).severity) {
      (doc as any).severity = this.normalizeSeverity((doc as any).severity);
    }

    // Legacy compatibility: some records were stored as "completed" even when a disease was found.
    if (doc.status === 'completed' && !this.isHealthyDiagnosisText(doc.diagnosis)) {
      (doc as any).status = 'detected';
    }

    return doc;
  }

  private normalizeSeverity(raw: any): 'low' | 'medium' | 'high' | 'critical' {
    const s = typeof raw === 'string' ? raw.toLowerCase().trim() : '';

    // Legacy/alternate synonyms
    if (s === 'mild') return 'low';
    if (s === 'moderate') return 'medium';
    if (s === 'severe') return 'high';

    if (s === 'low' || s === 'medium' || s === 'high' || s === 'critical') return s;
    return 'medium';
  }

  private buildTreatmentPlanFromSteps(
    steps: string[],
    severity: 'low' | 'medium' | 'high' | 'critical',
    urgency?: any,
    quarantineRecommended?: boolean
  ) {
    const u = typeof urgency === 'string' ? urgency : '';
    const defaultTimeframe =
      u === 'immediate'
        ? 'Immediate'
        : u === 'within_24h'
        ? 'Within 24 hours'
        : u === 'within_week'
        ? 'Within 1 week'
        : u === 'monitoring'
        ? 'Ongoing monitoring'
        : 'As needed';

    const basePriority: 'critical' | 'high' | 'medium' | 'low' =
      severity === 'critical'
        ? 'critical'
        : severity === 'high'
        ? 'high'
        : severity === 'medium'
        ? 'medium'
        : 'low';

    const inferCategory = (text: string): 'Immediate' | 'Medication' | 'Nutrition' | 'Isolation' | 'Monitoring' => {
      const t = text.toLowerCase();
      if (/(isolate|quarantine|separate|biosecurity)/.test(t)) return 'Isolation';
      if (/(antibiotic|antimicrobial|inject|injection|dose|dosage|mg\b|ml\b|tablet|capsule|medicine|medication|deworm|vaccine)/.test(t)) return 'Medication';
      if (/(feed|water|hydration|electrolyte|nutrition|vitamin|mineral)/.test(t)) return 'Nutrition';
      if (/(monitor|observe|check|record|track|temperature)/.test(t)) return 'Monitoring';
      return 'Immediate';
    };

    const tasks = (Array.isArray(steps) ? steps : [])
      .map((s) => String(s || '').trim())
      .filter(Boolean)
      .slice(0, 12)
      .map((step) => {
        const m = step.match(/^\s*\[([^\]]+)\]\s*(.*)$/);
        const timeframe = m?.[1]?.trim() || defaultTimeframe;
        const task = (m?.[2] || step).trim();
        const category = inferCategory(task);

        return {
          task,
          timeframe,
          category,
          priority: basePriority,
          isCompleted: false,
        };
      });

    if (quarantineRecommended && !tasks.some((t) => t.category === 'Isolation')) {
      tasks.unshift({
        task: 'Isolate affected animal(s) and enforce basic biosecurity to reduce spread risk.',
        timeframe: 'Immediate',
        category: 'Isolation',
        priority: basePriority === 'low' ? 'medium' : basePriority,
        isCompleted: false,
      });
    }

    return tasks;
  }

  /**
   * Create a new livestock health diagnosis
   */
  async createDiagnosis(
    livestockId: string,
    userId: string,
    imageBuffers: Buffer[],
    additionalSymptoms?: string[],
    affectedCount?: number
  ) {
    const livestock = await Livestock.findById(livestockId).populate('farmId');
    if (!livestock) {
      throw new Error('Livestock not found');
    }

    const farm = livestock.farmId as any;
    if (!farm) {
      throw new Error('Farm not found');
    }

    // Upload images to Cloudinary
    const uploadResults = await Promise.all(
      imageBuffers.map((buffer) =>
        new Promise<{ secure_url: string }>((resolve, reject) => {
          const stream = cloudinary.uploader.upload_stream(
            { folder: 'agroguardian/livestock-diagnoses', resource_type: 'image' },
            (error, result) => {
              if (error || !result) return reject(error || new Error('Upload failed'));
              resolve(result);
            }
          );
          stream.end(buffer);
        })
      )
    );

    const imageUrls = uploadResults.map(r => r.secure_url);

    // Determine batch info
    const isBatch = livestock.trackingType === 'batch';
    const batchSize = isBatch ? (livestock.quantity || 1) : undefined;
    const finalAffectedCount = isBatch && affectedCount ? affectedCount : undefined;

    // Create initial diagnosis record (processing)
    const diagnosis = await LivestockDiagnosis.create({
      livestockId: new Types.ObjectId(livestockId),
      farmId: farm._id,
      userId: new Types.ObjectId(userId),
      imageUrls,
      species: livestock.species,
      symptoms: additionalSymptoms || [],
      affectedCount: finalAffectedCount,
      batchSize,
      diagnosis: 'Analyzing...',
      confidence: 0,
      severity: 'low',
      treatment: [],
      prevention: [],
      status: 'processing',
      aiModel: getModelName(),
    });

    logger.info(`Livestock diagnosis initiated for ${livestock.name || livestock.tagId || livestockId}`);

    // Process asynchronously via queue
    await addLivestockDiagnosisJob({ diagnosisId: diagnosis._id.toString() });

    return diagnosis;
  }

  /**
   * Process a queued diagnosis job by ID
   */
  async processDiagnosisJob(diagnosisId: string) {
    const diagnosis = await LivestockDiagnosis.findById(diagnosisId);
    if (!diagnosis) {
      throw new Error('Diagnosis not found');
    }

    const livestock = await Livestock.findById(diagnosis.livestockId).populate('farmId');
    if (!livestock) {
      throw new Error('Livestock not found');
    }

    const farm = livestock.farmId as any;

    return this.processLivestockDiagnosis(
      diagnosisId,
      diagnosis.imageUrls || [],
      livestock,
      farm,
      diagnosis.userId.toString(),
      (diagnosis as any).affectedCount,
      (diagnosis as any).batchSize
    );
  }

  /**
   * Process the diagnosis using AI
   */
  private async processLivestockDiagnosis(
    diagnosisId: string,
    imageUrls: string[],
    livestock: any,
    farm: any,
    userId: string,
    affectedCount?: number,
    batchSize?: number
  ) {
    try {
      // Get health history
      const healthRecords = await livestockHealthService.getAllHealthRecords(livestock._id.toString());
      
      // Get weather data
      const latestWeather = await WeatherData.findOne({ farmId: farm._id }).sort({ timestamp: -1 });

      // Calculate age
      let age = 'Unknown';
      if (livestock.dateOfBirth) {
        const ageMs = Date.now() - new Date(livestock.dateOfBirth).getTime();
        const years = Math.floor(ageMs / (365.25 * 24 * 60 * 60 * 1000));
        const months = Math.floor((ageMs % (365.25 * 24 * 60 * 60 * 1000)) / (30.44 * 24 * 60 * 60 * 1000));
        age = years > 0 ? `${years} years ${months} months` : `${months} months`;
      }

      // Build health history summary
      const healthHistory = [
        `Vaccinations: ${healthRecords.vaccinations.length}`,
        `Treatments: ${healthRecords.treatments.length}`,
        `Past illnesses: ${healthRecords.illnesses.length}`,
        healthRecords.illnesses.length > 0 
          ? `Recent illness: ${healthRecords.illnesses[0]?.condition || 'Unknown'}`
          : ''
      ].filter(Boolean).join(', ');

      // Build batch info for the prompt
      let batchInfo = '';
      if (batchSize && batchSize > 1) {
        const affectedPercent = affectedCount 
          ? Math.round((affectedCount / batchSize) * 100)
          : 0;
        batchInfo = `
**Batch Information:**
- This is a BATCH of ${batchSize} animals
- Affected animals: ${affectedCount || 'Unknown'} (${affectedPercent}% of batch)
- IMPORTANT: Consider disease spread risk within the batch and recommend isolation/quarantine measures`;
      }

      // Prepare the prompt
      const prompt = LIVESTOCK_DIAGNOSIS_PROMPT
        .replace('{species}', livestock.species)
        .replace('{breed}', livestock.breed || 'Unknown')
        .replace('{age}', age)
        .replace('{healthStatus}', livestock.healthStatus)
        .replace('{healthHistory}', healthHistory || 'No prior records')
        .replace('{batchInfo}', batchInfo)
        .replace('{location}', `${farm.location?.city || ''}, ${farm.location?.country || ''}`)
        .replace('{weather}', latestWeather?.current?.weatherDescription || 'Unknown')
        .replace('{temperature}', String(latestWeather?.current?.temperature || 'Unknown'))
        .replace('{humidity}', String(latestWeather?.current?.humidity || 'Unknown'));

      // Call AI with images (do not fail the whole worker if the provider is down / rate-limited)
      let aiResponse = '';
      let parsedResponse: any;

      try {
        aiResponse = await analyzeImageWithGemini(imageUrls, prompt);
      } catch (e: any) {
        logger.warn('AI image diagnosis failed; returning safe fallback', {
          status: e?.status,
          code: e?.code,
          message: e?.message,
          providerMessage: e?.error?.message || e?.response?.data?.error?.message,
        });

        parsedResponse = {
          diagnosis: 'AI image analysis is temporarily unavailable (model unavailable / rate-limited / insufficient credits).',
          confidence: 0.2,
          severity: 'medium',
          symptoms: [],
          treatment: [
            'Isolate the sick animal(s) and separate equipment/boots between pens.',
            'Provide clean water, shade/ventilation, and monitor temperature if possible.',
            'Contact a veterinarian/extension officer for an on-site assessment.'
          ],
          prevention: ['Improve hygiene and biosecurity; reduce overcrowding; quarantine new animals.'],
          urgency: 'within_24h',
          veterinaryRequired: true,
          quarantineRecommended: true,
          followUpDays: 1,
          additionalNotes: 'If this keeps happening, change OpenRouter models, reduce AI_MAX_TOKENS, add credits, or use BYOK in OpenRouter integrations.'
        };
      }

      // Parse AI response
      if (!parsedResponse) {
        try {
          // Try to extract JSON from the response
          const jsonMatch = aiResponse.match(/\{[\s\S]*\}/);
          if (jsonMatch) {
            parsedResponse = JSON.parse(jsonMatch[0]);
          } else {
            throw new Error('No JSON found in response');
          }
        } catch (parseError) {
          logger.warn('Failed to parse AI response as JSON, using fallback');
          parsedResponse = {
            diagnosis: aiResponse.substring(0, 500),
            confidence: 0.5,
            severity: 'moderate',
            symptoms: [],
            treatment: ['Please consult a veterinarian for accurate diagnosis'],
            prevention: ['Regular health monitoring'],
            urgency: 'within_24h',
            veterinaryRequired: true,
            quarantineRecommended: false,
            followUpDays: 3,
            additionalNotes: 'AI could not provide structured diagnosis. Manual review recommended.'
          };
        }
      }

      // Convert treatment objects to strings if needed
      let treatmentSteps: string[] = [];
      if (Array.isArray(parsedResponse.treatment)) {
        treatmentSteps = parsedResponse.treatment.map((t: any) => {
          if (typeof t === 'string') return t;
          // Convert object to readable string
          return `[${t.timing || 'As needed'}] ${t.action}${t.notes ? ` (${t.notes})` : ''}`;
        });
      }

      // Convert prevention to strings if needed
      let preventionSteps: string[] = [];
      if (Array.isArray(parsedResponse.prevention)) {
        preventionSteps = parsedResponse.prevention.map((p: any) => {
          if (typeof p === 'string') return p;
          return p.action || p.description || String(p);
        });
      }

      // Herd/flock protection advice for contagious cases (vaccination only when applicable)
      if (batchSize && batchSize > 1 || parsedResponse.quarantineRecommended || parsedResponse.spreadRisk) {
        try {
          const herdAdvice = getHerdPreventionAdvice({ species: livestock.species, likelyCondition: parsedResponse.diagnosis });
          preventionSteps = Array.from(new Set([...(preventionSteps || []), ...herdAdvice]));
        } catch {
          // best-effort
        }
      }

      const normalizedSeverity = this.normalizeSeverity(parsedResponse.severity);

      const statusAfterAnalysis = this.isHealthyDiagnosisText(parsedResponse.diagnosis)
        ? 'completed'
        : 'detected';

      const treatmentPlan = statusAfterAnalysis === 'completed'
        ? []
        : this.buildTreatmentPlanFromSteps(
            treatmentSteps,
            normalizedSeverity,
            parsedResponse.urgency,
            Boolean(parsedResponse.quarantineRecommended)
          );

      // Update diagnosis record
      const updatedDiagnosis = await LivestockDiagnosis.findByIdAndUpdate(
        diagnosisId,
        {
          diagnosis: parsedResponse.diagnosis,
          confidence: parsedResponse.confidence || 0.5,
          severity: normalizedSeverity,
          symptoms: parsedResponse.symptoms || [],
          possibleConditions: parsedResponse.possibleConditions || [],
          treatment: treatmentSteps,
          treatmentPlan,
          prevention: preventionSteps,
          urgency: parsedResponse.urgency || 'within_24h',
          veterinaryRequired: parsedResponse.veterinaryRequired ?? true,
          quarantineRecommended: parsedResponse.quarantineRecommended ?? false,
          followUpDays: parsedResponse.followUpDays || 7,
          additionalNotes: parsedResponse.additionalNotes,
          status: statusAfterAnalysis,
          analyzedAt: new Date()
        },
        { new: true }
      );

      // Update livestock health status based on severity
      let newHealthStatus = livestock.healthStatus;
      if (normalizedSeverity === 'critical') {
        newHealthStatus = 'critical';
      } else if (normalizedSeverity === 'high') {
        newHealthStatus = 'sick';
      } else if (normalizedSeverity === 'medium') {
        newHealthStatus = 'under_treatment';
      }

      if (newHealthStatus !== livestock.healthStatus) {
        await Livestock.findByIdAndUpdate(livestock._id, { healthStatus: newHealthStatus });
      }

      // Send notification
      await createNotification(
        userId,
        'Livestock Diagnosis Complete',
        `Health assessment for ${livestock.name || livestock.tagId || livestock.species} is ready. Severity: ${parsedResponse.severity}`,
        'diagnosis',
        `/livestock/${livestock._id}`
      );

      // Send email for critical cases
      if (parsedResponse.severity === 'critical' || parsedResponse.urgency === 'immediate') {
        const user = await User.findById(userId);
        if (user) {
          await sendBrevoEmail(
            user.email,
            '🚨 Urgent: Critical Livestock Health Alert',
            `<h2>Critical Health Alert</h2>
            <p>Your ${livestock.species} (${livestock.name || livestock.tagId}) requires immediate attention.</p>
            <p><strong>Diagnosis:</strong> ${parsedResponse.diagnosis}</p>
            <p><strong>Severity:</strong> ${parsedResponse.severity}</p>
            <p><strong>Action Required:</strong> ${parsedResponse.veterinaryRequired ? 'Contact a veterinarian immediately' : 'Follow treatment plan'}</p>
            <a href="${process.env.FRONTEND_URL}/livestock/${livestock._id}">View Full Diagnosis</a>`
          );
        }
      }

      logger.info(`Livestock diagnosis completed for ${livestock._id}: ${parsedResponse.diagnosis}`);
      return updatedDiagnosis;
    } catch (error) {
      logger.error('Livestock diagnosis processing error', error);
      
      await LivestockDiagnosis.findByIdAndUpdate(diagnosisId, {
        status: 'failed',
        additionalNotes: error instanceof Error ? error.message : 'Processing failed'
      });

      throw error;
    }
  }

  /**
   * Get diagnosis by ID
   */
  private readonly diagnosisLivestockPopulateFields =
    'name tagId species breed healthStatus imageUrls trackingType quantity batchId poultryType fishType';

  async getDiagnosis(diagnosisId: string, userId: string) {
    const diagnosis = await LivestockDiagnosis.findOne({
      _id: diagnosisId,
      userId: new Types.ObjectId(userId)
    }).populate('livestockId', this.diagnosisLivestockPopulateFields);

    if (!diagnosis) {
      throw new Error('Diagnosis not found');
    }

    // Normalize legacy "completed" records that actually contain a disease.
    this.normalizeDiagnosisStatus(diagnosis as any);

    // Ensure older diagnoses have a tickable treatment plan persisted.
    const tp = (diagnosis as any).treatmentPlan;
    const tr = (diagnosis as any).treatment;
    const st = (diagnosis as any).status;
    if (
      (!Array.isArray(tp) || tp.length === 0) &&
      Array.isArray(tr) &&
      tr.length > 0 &&
      typeof st === 'string' &&
      ['detected', 'treating', 'treated', 'resolved'].includes(st)
    ) {
      (diagnosis as any).treatmentPlan = this.buildTreatmentPlanFromSteps(
        tr,
        this.normalizeSeverity((diagnosis as any).severity),
        (diagnosis as any).urgency,
        Boolean((diagnosis as any).quarantineRecommended)
      );
      await (diagnosis as any).save();
    }

    return diagnosis as any;
  }

  /**
   * Get all diagnoses for a livestock
   */
  async getDiagnosesByLivestock(livestockId: string) {
    const diagnoses = await LivestockDiagnosis.find({ livestockId: new Types.ObjectId(livestockId) })
      .populate('livestockId', this.diagnosisLivestockPopulateFields)
      .sort({ createdAt: -1 });
    return diagnoses.map(d => this.normalizeDiagnosisStatus(d as any));
  }

  /**
   * Get all diagnoses for a farm
   */
  async getDiagnosesByFarm(farmId: string, options: { status?: string; limit?: number } = {}) {
    const query: any = { farmId: new Types.ObjectId(farmId) };
    if (options.status) {
      query.status = options.status;
    }

    const diagnoses = await LivestockDiagnosis.find(query)
      .populate('livestockId', this.diagnosisLivestockPopulateFields)
      .sort({ createdAt: -1 })
      .limit(options.limit || 50);

    return diagnoses.map(d => this.normalizeDiagnosisStatus(d as any));
  }

  /**
   * Chat about a diagnosis
   */
  async chatAboutDiagnosis(
    diagnosisId: string,
    userId: string,
    message: string
  ) {
    const diagnosis = await LivestockDiagnosis.findOne({
      _id: diagnosisId,
      userId: new Types.ObjectId(userId)
    }).populate('livestockId');

    if (!diagnosis) {
      throw new Error('Diagnosis not found');
    }

    // Normalize legacy values (e.g., severity "moderate") before using/saving.
    this.normalizeDiagnosisStatus(diagnosis as any);

    const livestock = diagnosis.livestockId as any;

    // Build species-aware system prompt (inject specialist module)
    const dob = (livestock as any)?.dateOfBirth ? new Date((livestock as any).dateOfBirth) : null;
    const ageDays = dob && Number.isFinite(dob.getTime())
      ? Math.max(0, Math.floor((Date.now() - dob.getTime()) / (1000 * 60 * 60 * 24)))
      : null;

    const extraContextLines: string[] = [];
    if ((livestock as any)?.healthStatus) extraContextLines.push(`Health Status: ${(livestock as any).healthStatus}`);
    if ((livestock as any)?.trackingType) extraContextLines.push(`Tracking Type: ${(livestock as any).trackingType}`);
    if (typeof (livestock as any)?.quantity === 'number') extraContextLines.push(`Batch Size: ${(livestock as any).quantity}`);
    if (typeof ageDays === 'number') {
      extraContextLines.push(
        (livestock as any)?.species === 'poultry'
          ? `Age: ${ageDays} days (${Math.floor(ageDays / 7)} weeks)`
          : `Age: ${ageDays} days`
      );
    }

    const systemPrompt = buildVetDiagnosisChatSystemPrompt({
      species: livestock?.species || 'Unknown',
      breed: livestock?.breed || 'Unknown',
      name: livestock?.name || livestock?.tagId || 'Unknown',
      diagnosis: (diagnosis as any)?.diagnosis,
      severity: (diagnosis as any)?.severity,
      symptoms: Array.isArray((diagnosis as any)?.symptoms) ? (diagnosis as any).symptoms.join(', ') : 'None recorded',
      poultryType: (livestock as any)?.poultryType,
      extraContext: extraContextLines.length ? extraContextLines.join('\n') : undefined,
    });

    // Get chat history
    const chatHistory = (diagnosis as any).chatMessages?.map((msg: any) => ({
      role: msg.role as 'user' | 'assistant',
      content: msg.content,
      reasoning_details: msg.reasoning_details,
    })) || [];

    // Get AI response
    const ai = await chatWithContextDetailed(message, chatHistory, systemPrompt);
    let aiResponse = ai.content;
    let aiReasoningDetails = ai.reasoning_details;

    // Parse/validate structured JSON and convert to user-friendly text
    let aiStructured: any;
    try {
      aiStructured = parseVetAiStructuredResponse(aiResponse);

      // Add herd/flock protection advice (vaccination only when applicable)
      try {
        const herdAdvice = getHerdPreventionAdvice({ species: livestock?.species || 'unknown', likelyCondition: aiStructured?.likelyCondition });
        if (Array.isArray(herdAdvice) && herdAdvice.length) {
          aiStructured.biosecurity = Array.isArray(aiStructured.biosecurity)
            ? Array.from(new Set([...aiStructured.biosecurity, ...herdAdvice]))
            : herdAdvice;
        }
      } catch {
        // best-effort
      }

      aiResponse = formatVetAiStructuredResponseToText(aiStructured);
    } catch (e: any) {
      try {
        const repair = await chatWithContextDetailed(
          buildVetJsonRepairMessage({ userMessage: message, invalidOutput: aiResponse }),
          chatHistory,
          systemPrompt
        );
        aiReasoningDetails = repair.reasoning_details ?? aiReasoningDetails;
        aiStructured = parseVetAiStructuredResponse(repair.content);

        // Add herd/flock protection advice (vaccination only when applicable)
        try {
          const herdAdvice = getHerdPreventionAdvice({ species: livestock?.species || 'unknown', likelyCondition: aiStructured?.likelyCondition });
          if (Array.isArray(herdAdvice) && herdAdvice.length) {
            aiStructured.biosecurity = Array.isArray(aiStructured.biosecurity)
              ? Array.from(new Set([...aiStructured.biosecurity, ...herdAdvice]))
              : herdAdvice;
          }
        } catch {
          // best-effort
        }

        aiResponse = formatVetAiStructuredResponseToText(aiStructured);
      } catch (e2: any) {
        logger.warn(`Diagnosis Vet AI JSON parse/repair failed: ${e2?.message || e2}`);
      }
    }

    // Save chat message
    (diagnosis as any).chatMessages = (diagnosis as any).chatMessages || [];
    (diagnosis as any).chatMessages.push(
      { role: 'user', content: message, timestamp: new Date() },
      { role: 'assistant', content: aiResponse, structured: aiStructured, reasoning_details: aiReasoningDetails, timestamp: new Date() }
    );
    await diagnosis.save();

    return {
      userMessage: message,
      aiResponse,
      aiStructured,
      aiReasoningDetails,
      totalMessages: ((diagnosis as any).chatMessages || []).length
    };
  }

  /**
   * Get chat history for a diagnosis
   */
  async getChatHistory(diagnosisId: string, userId: string) {
    const diagnosis = await LivestockDiagnosis.findOne({
      _id: diagnosisId,
      userId: new Types.ObjectId(userId)
    }).select('chatMessages');

    if (!diagnosis) {
      throw new Error('Diagnosis not found');
    }

    return (diagnosis as any).chatMessages || [];
  }

  /**
   * Toggle a treatment-plan task and auto-advance the diagnosis status.
   * - Any incomplete task => status "treating"
   * - All tasks completed => status "treated" (farmer should mark "resolved" only after full recovery)
   */
  async toggleTreatmentPlanTask(diagnosisId: string, userId: string, taskId: string) {
    const diagnosis = await LivestockDiagnosis.findOne({
      _id: new Types.ObjectId(diagnosisId),
      userId: new Types.ObjectId(userId),
    });

    if (!diagnosis) {
      throw new Error('Diagnosis not found');
    }

    // Normalize legacy "completed" records that actually contain a disease.
    this.normalizeDiagnosisStatus(diagnosis as any);

    // Do not allow ticking tasks for healthy/failed diagnoses.
    if ((diagnosis as any).status === 'completed' || (diagnosis as any).status === 'failed') {
      return diagnosis;
    }

    // If a legacy record has no plan yet, generate it from the treatment steps.
    if (
      (!Array.isArray((diagnosis as any).treatmentPlan) || (diagnosis as any).treatmentPlan.length === 0) &&
      Array.isArray((diagnosis as any).treatment) &&
      (diagnosis as any).treatment.length > 0
    ) {
      (diagnosis as any).treatmentPlan = this.buildTreatmentPlanFromSteps(
        (diagnosis as any).treatment,
        this.normalizeSeverity((diagnosis as any).severity),
        (diagnosis as any).urgency,
        Boolean((diagnosis as any).quarantineRecommended)
      );
    }

    const plan = (diagnosis as any).treatmentPlan || [];
    const task = typeof plan?.id === 'function' ? plan.id(taskId) : null;
    if (!task) {
      throw new Error('Treatment task not found');
    }

    task.isCompleted = !task.isCompleted;

    const anyCompleted = plan.some((t: any) => Boolean(t?.isCompleted));
    const allDone = plan.length > 0 && plan.every((t: any) => Boolean(t?.isCompleted));

    if (allDone) {
      (diagnosis as any).status = "treated";
    } else if (anyCompleted) {
      (diagnosis as any).status = "treating";
    } else {
      // If nothing is completed anymore, it's back to 'detected'
      (diagnosis as any).status = "detected";
    }

    await (diagnosis as any).save();
    return diagnosis;
  }

  /**
   * Update diagnosis status
   */
  async updateDiagnosisStatus(
    diagnosisId: string,
    userId: string,
    status: 'detected' | 'treating' | 'treated' | 'resolved'
  ) {
    const diagnosis = await LivestockDiagnosis.findOneAndUpdate(
      { _id: diagnosisId, userId: new Types.ObjectId(userId) },
      { status },
      { new: true }
    );

    if (!diagnosis) {
      throw new Error('Diagnosis not found');
    }

    // Update livestock health status if resolved
    if (status === 'resolved') {
      await Livestock.findByIdAndUpdate(diagnosis.livestockId, {
        healthStatus: 'healthy'
      });
    }

    return diagnosis;
  }
}

export const livestockDiagnosisService = new LivestockDiagnosisService();
