import { VetConsultation } from '../Models/LivestockManagement';
import Livestock from '../Models/Livestock';
import Farm from '../Models/Farm';
import WeatherData from '../Models/WeatherData';
import { Types } from 'mongoose';
import { IVetConsultation } from '../Types/livestock.types';
import { livestockHealthService } from './livestock-health.service';
import { chatWithContextDetailed, chatWithImagesDetailed } from '../Utils/geminiClient';
import { buildVetConsultationSystemPrompt } from '../Utils/vetPromptRouter';
import { getHerdPreventionAdvice } from '../Utils/herdPreventionAdvice';
import { formatVetAiStructuredResponseToText, parseVetAiStructuredResponse } from '../Utils/vetStructuredResponse';
import cloudinary from '../Config/cloudinary';
import logger from '../Utils/logger';

// NOTE: Vet AI prompts are generated by buildVetConsultationSystemPrompt() (species-specialized).

const buildVetJsonRepairMessage = (args: { userMessage: string; invalidOutput: string }) => {
  const bad = String(args.invalidOutput || '').slice(0, 6000);
  return `Your previous response was not valid JSON or did not match the required schema.\n\nFarmer message:\n${args.userMessage}\n\nInvalid output (truncated):\n${bad}\n\nReturn ONLY a corrected JSON object that matches the schema. No markdown. No code fences.`;
};

export class VetConsultationService {
  /**
   * Start a new consultation
   */
  async startConsultation(data: {
    farmId: string;
    userId: string;
    livestockId?: string;
    species: string;
    initialMessage: string;
    imageBuffers?: Buffer[];
  }): Promise<IVetConsultation> {
    // Upload images if provided
    let imageUrls: string[] = [];
    if (data.imageBuffers && data.imageBuffers.length > 0) {
      const uploadResults = await Promise.all(
        data.imageBuffers.map((buffer) =>
          new Promise<{ secure_url: string }>((resolve, reject) => {
            const stream = cloudinary.uploader.upload_stream(
              { folder: 'agroguardian/vet-consultations', resource_type: 'image' },
              (error, result) => {
                if (error || !result) return reject(error || new Error('Upload failed'));
                resolve(result);
              }
            );
            stream.end(buffer);
          })
        )
      );
      imageUrls = uploadResults.map(r => r.secure_url);
    }

    // Build context
    const context = await this.buildContext(data.farmId, data.livestockId, data.species);

    // Species-aware prompt routing (inject specialist module)
    let poultryType: string | undefined;
    if (data.livestockId) {
      try {
        const livestock = await Livestock.findById(data.livestockId).select('poultryType');
        poultryType = (livestock as any)?.poultryType;
      } catch {
        // best-effort
      }
    }

    // Get AI response
    const systemPrompt = buildVetConsultationSystemPrompt({
      context,
      species: data.species,
      poultryType,
    });

    let aiResponse: string;
    let aiReasoningDetails: any;
    if (imageUrls.length > 0) {
      const ai = await chatWithImagesDetailed(systemPrompt, data.initialMessage, imageUrls, []);
      aiResponse = ai.content;
      aiReasoningDetails = ai.reasoning_details;
    } else {
      const ai = await chatWithContextDetailed(data.initialMessage, [], systemPrompt);
      aiResponse = ai.content;
      aiReasoningDetails = ai.reasoning_details;
    }

    // Parse/validate structured JSON and convert to user-friendly text
    let aiStructured: any;
    try {
      aiStructured = parseVetAiStructuredResponse(aiResponse);
      aiResponse = formatVetAiStructuredResponseToText(aiStructured);
    } catch (e: any) {
      try {
        const repair = await chatWithContextDetailed(
          buildVetJsonRepairMessage({ userMessage: data.initialMessage, invalidOutput: aiResponse }),
          [],
          systemPrompt
        );
        aiReasoningDetails = repair.reasoning_details ?? aiReasoningDetails;
        aiStructured = parseVetAiStructuredResponse(repair.content);
        aiResponse = formatVetAiStructuredResponseToText(aiStructured);
      } catch (e2: any) {
        logger.warn(`Vet AI JSON parse/repair failed: ${e2?.message || e2}`);
      }
    }

    // Add herd/flock protection advice (vaccination only when applicable)
    if (aiStructured) {
      try {
        const herdAdvice = getHerdPreventionAdvice({ species: data.species, likelyCondition: aiStructured?.likelyCondition });
        if (Array.isArray(herdAdvice) && herdAdvice.length) {
          aiStructured.biosecurity = Array.isArray(aiStructured.biosecurity)
            ? Array.from(new Set([...aiStructured.biosecurity, ...herdAdvice]))
            : herdAdvice;
          aiResponse = formatVetAiStructuredResponseToText(aiStructured);
        }
      } catch {
        // best-effort
      }
    }

    // Create consultation
    const consultation = await VetConsultation.create({
      farmId: new Types.ObjectId(data.farmId),
      userId: new Types.ObjectId(data.userId),
      livestockId: data.livestockId ? new Types.ObjectId(data.livestockId) : undefined,
      species: data.species,
      status: 'active',
      messages: [
        {
          role: 'user',
          content: data.initialMessage,
          imageUrls: imageUrls.length > 0 ? imageUrls : undefined,
          timestamp: new Date()
        },
        {
          role: 'assistant',
          content: aiResponse,
          structured: aiStructured,
          reasoning_details: aiReasoningDetails,
          timestamp: new Date()
        }
      ]
    });

    logger.info(`Vet consultation started: ${consultation._id}`);
    return consultation;
  }

  /**
   * Send a message in an existing consultation
   */
  async sendMessage(
    consultationId: string,
    userId: string,
    message: string,
    imageBuffers?: Buffer[]
  ): Promise<{ consultation: IVetConsultation; aiResponse: string; aiReasoningDetails?: any; aiStructured?: any }> {
    const consultation = await VetConsultation.findOne({
      _id: consultationId,
      userId: new Types.ObjectId(userId)
    });

    if (!consultation) {
      throw new Error('Consultation not found');
    }

    // Upload images if provided
    let imageUrls: string[] = [];
    if (imageBuffers && imageBuffers.length > 0) {
      const uploadResults = await Promise.all(
        imageBuffers.map((buffer) =>
          new Promise<{ secure_url: string }>((resolve, reject) => {
            const stream = cloudinary.uploader.upload_stream(
              { folder: 'agroguardian/vet-consultations', resource_type: 'image' },
              (error, result) => {
                if (error || !result) return reject(error || new Error('Upload failed'));
                resolve(result);
              }
            );
            stream.end(buffer);
          })
        )
      );
      imageUrls = uploadResults.map(r => r.secure_url);
    }

    // Build context
    const context = await this.buildContext(
      consultation.farmId.toString(),
      consultation.livestockId?.toString(),
      consultation.species
    );

    // Build chat history
    const chatHistory = consultation.messages.map(msg => ({
      role: msg.role as 'user' | 'assistant',
      content: msg.content,
      imageUrls: msg.imageUrls,
      reasoning_details: (msg as any).reasoning_details,
    }));

    // Species-aware prompt routing (inject specialist module)
    let poultryType: string | undefined;
    if (consultation.livestockId) {
      try {
        const livestock = await Livestock.findById(consultation.livestockId).select('poultryType');
        poultryType = (livestock as any)?.poultryType;
      } catch {
        // best-effort
      }
    }

    // Get AI response
    const systemPrompt = buildVetConsultationSystemPrompt({
      context,
      species: consultation.species,
      poultryType,
    });

    let aiResponse: string;
    let aiReasoningDetails: any;
    if (imageUrls.length > 0) {
      const ai = await chatWithImagesDetailed(systemPrompt, message, imageUrls, chatHistory);
      aiResponse = ai.content;
      aiReasoningDetails = ai.reasoning_details;
    } else {
      const ai = await chatWithContextDetailed(message, chatHistory, systemPrompt);
      aiResponse = ai.content;
      aiReasoningDetails = ai.reasoning_details;
    }

    // Parse/validate structured JSON and convert to user-friendly text
    let aiStructured: any;
    try {
      aiStructured = parseVetAiStructuredResponse(aiResponse);
      aiResponse = formatVetAiStructuredResponseToText(aiStructured);
    } catch (e: any) {
      try {
        const repair = await chatWithContextDetailed(
          buildVetJsonRepairMessage({ userMessage: message, invalidOutput: aiResponse }),
          chatHistory,
          systemPrompt
        );
        aiReasoningDetails = repair.reasoning_details ?? aiReasoningDetails;
        aiStructured = parseVetAiStructuredResponse(repair.content);
        aiResponse = formatVetAiStructuredResponseToText(aiStructured);
      } catch (e2: any) {
        logger.warn(`Vet AI JSON parse/repair failed: ${e2?.message || e2}`);
      }
    }

    // Add herd/flock protection advice (vaccination only when applicable)
    if (aiStructured) {
      try {
        const herdAdvice = getHerdPreventionAdvice({ species: consultation.species, likelyCondition: aiStructured?.likelyCondition });
        if (Array.isArray(herdAdvice) && herdAdvice.length) {
          aiStructured.biosecurity = Array.isArray(aiStructured.biosecurity)
            ? Array.from(new Set([...aiStructured.biosecurity, ...herdAdvice]))
            : herdAdvice;
          aiResponse = formatVetAiStructuredResponseToText(aiStructured);
        }
      } catch {
        // best-effort
      }
    }

    // Add messages
    consultation.messages.push(
      {
        role: 'user',
        content: message,
        imageUrls: imageUrls.length > 0 ? imageUrls : undefined,
        timestamp: new Date()
      },
      {
        role: 'assistant',
        content: aiResponse,
        structured: aiStructured,
        reasoning_details: aiReasoningDetails,
        timestamp: new Date()
      }
    );

    await consultation.save();

    return { consultation, aiResponse, aiReasoningDetails, aiStructured };
  }

  /**
   * Get consultation by ID
   */
  async getConsultation(consultationId: string, userId: string): Promise<IVetConsultation | null> {
    return VetConsultation.findOne({
      _id: consultationId,
      userId: new Types.ObjectId(userId)
    }).populate('livestockId', 'name tagId species breed healthStatus');
  }

  /**
   * Get all consultations for a farm
   */
  async getConsultations(farmId: string, options: {
    status?: string;
    livestockId?: string;
    limit?: number;
  } = {}): Promise<IVetConsultation[]> {
    const query: any = { farmId: new Types.ObjectId(farmId) };
    
    if (options.status) query.status = options.status;
    if (options.livestockId) query.livestockId = new Types.ObjectId(options.livestockId);

    return VetConsultation.find(query)
      .populate('livestockId', 'name tagId species breed')
      .sort({ updatedAt: -1 })
      .limit(options.limit || 50);
  }

  /**
   * Update consultation (resolve, archive, add summary)
   */
  async updateConsultation(
    consultationId: string,
    userId: string,
    data: Partial<Pick<IVetConsultation, 'status' | 'title' | 'summary' | 'issueType' | 'severity'>>
  ): Promise<IVetConsultation | null> {
    return VetConsultation.findOneAndUpdate(
      { _id: consultationId, userId: new Types.ObjectId(userId) },
      { $set: data },
      { new: true }
    );
  }

  /**
   * Delete consultation
   */
  async deleteConsultation(consultationId: string, userId: string): Promise<boolean> {
    const result = await VetConsultation.findOneAndDelete({
      _id: consultationId,
      userId: new Types.ObjectId(userId)
    });
    return !!result;
  }

  /**
   * Build context string for AI
   */
  private async buildContext(farmId: string, livestockId?: string, species?: string): Promise<string> {
    const contextParts: string[] = [];

    // Get farm info
    const farm = await Farm.findById(farmId);
    if (farm) {
      contextParts.push(`Farm: ${farm.name}`);
      if (farm.location) {
        contextParts.push(`Location: ${farm.location.city}, ${farm.location.country}`);
      }
    }

    // Get weather
    const weather = await WeatherData.findOne({ farmId: new Types.ObjectId(farmId) }).sort({ timestamp: -1 });
    if (weather?.current) {
      contextParts.push(`Weather: ${weather.current.weatherDescription}, ${weather.current.temperature}°C, ${weather.current.humidity}% humidity`);
    }

    // Get livestock info if specific animal
    if (livestockId) {
      const livestock = await Livestock.findById(livestockId);
      if (livestock) {
        contextParts.push(`Animal: ${livestock.name || livestock.tagId || 'Unknown'}`);
        if ((livestock as any).species === 'poultry') {
          contextParts.push(
            `Species: ${livestock.species}, Poultry Type: ${(livestock as any).poultryType || 'Unknown'}, Breed: ${livestock.breed || 'Unknown'}`
          );
        } else {
          contextParts.push(`Species: ${livestock.species}, Breed: ${livestock.breed || 'Unknown'}`);
        }
        contextParts.push(`Health Status: ${livestock.healthStatus}`);

        const trackingType = (livestock as any).trackingType;
        if (trackingType) contextParts.push(`Tracking Type: ${trackingType}`);

        const quantity = (livestock as any).quantity;
        if (typeof quantity === 'number' && quantity > 0) contextParts.push(`Batch Size: ${quantity}`);

        if ((livestock as any).batchId) contextParts.push(`Batch ID: ${(livestock as any).batchId}`);
        if ((livestock as any).housingUnit) contextParts.push(`Housing Unit: ${(livestock as any).housingUnit}`);

        if (livestock.weight) contextParts.push(`Weight: ${livestock.weight}kg`);

        if (livestock.dateOfBirth) {
          const dob = new Date(livestock.dateOfBirth);
          const ageDays = Number.isFinite(dob.getTime())
            ? Math.max(0, Math.floor((Date.now() - dob.getTime()) / (1000 * 60 * 60 * 24)))
            : null;

          if (ageDays !== null) {
            if ((livestock as any).species === 'poultry') {
              const weeks = Math.floor(ageDays / 7);
              contextParts.push(`Age: ${ageDays} days (${weeks} weeks)`);
            } else {
              const years = Math.floor(ageDays / 365.25);
              const months = Math.floor((ageDays % 365.25) / 30.44);
              contextParts.push(`Age: ${years > 0 ? `${years}y ${months}m` : `${months} months`}`);
            }
          }
        }

        // Get recent health records
        try {
          const healthRecords = await livestockHealthService.getAllHealthRecords(livestockId);
          if (healthRecords.vaccinations.length > 0) {
            contextParts.push(
              `Recent vaccinations: ${healthRecords.vaccinations
                .slice(0, 3)
                .map(v => v.vaccineName)
                .join(', ')}`
            );
          }

          if (healthRecords.dewormings?.length > 0) {
            const last = healthRecords.dewormings[0] as any;
            contextParts.push(`Recent deworming: ${last?.dewormerName || last?.productName || 'recorded'}`);
          }

          if (healthRecords.checkups?.length > 0) {
            const last = healthRecords.checkups[0] as any;
            contextParts.push(`Recent checkup: ${last?.findings || 'recorded'}`);
          }

          if (healthRecords.treatments.length > 0) {
            const activeTreatments = healthRecords.treatments.filter(t => t.status === 'ongoing');
            if (activeTreatments.length > 0) {
              contextParts.push(`Active treatments: ${activeTreatments.map(t => t.condition).join(', ')}`);
            }
          }

          if (healthRecords.illnesses.length > 0) {
            const activeIllnesses = healthRecords.illnesses.filter(i => i.status !== 'resolved');
            if (activeIllnesses.length > 0) {
              contextParts.push(`Current illnesses: ${activeIllnesses.map(i => i.condition).join(', ')}`);
            }
          }
        } catch (e) {
          // Health records may not exist
        }
      }
    } else if (species) {
      contextParts.push(`Species: ${species}`);
    }

    return contextParts.join('\n');
  }
}

export const vetConsultationService = new VetConsultationService();
